[input]
path = "./"
file_types = ["cr2", "cr3", "raf"]

[output]
base = "hello"
path = "{yyyy}/{yyyy}-{MM}-{dd}"
filename = "{yyyy}-{MM}-{dd} {HH}:{mm}:{ss} {seq} {filename}.{extension}"
overwrite = false
